sudo: required
language: android

env:
  matrix:
    - ANDROID_API=28 ANDROID_BUILD_TOOLS=28.0.3
  
  global:
    # GCLOUD_ACCOUNT
    - secure: "abjdXordIBzQ7sAaLgx3b7EqVW6PL/IhzvD236neCClHTeHVsbi0PiM6+V7RJFiOYVfO3BTCacI6d5CVnpXL2cX5FrvTQdpFjh1yQymGb6USyFKzZLkGigWyjxqCEUaef2kz4FslyGBI5Z4+DwV5enXuFVXzL0EVYmgk6O3zrvSUNutyo41VV+P9fAl+wDc49DF3Q72gMyxrYgp2U1TPiCJsOAaI12npia1lPCJ5kuJ//3FV8naJ2XVy8H6nx+UJMWIVDlM5R82eNl56kP6fOYQqkitHxliuBJkYX9G3m2Of+o6K/S7AK3r3oTtRNTIS3Fzgbj5ahrAgv9fmaOID1MJA+qB7Km6dXedGo/ZnUKluBAUtG4m8tr4VpU+9AEamjqTKB5crSOh2kVWbu0vUAs//MwW1ptEj2cryI0Yy/IdROk35J4yYlWmWqCfYggKZdSZ189n0pGVVDmlQw6iNXFUQwbBiCf9yGYIJPbgLZ0Q/hdRy2R4YEi6Mi1E0VLLCpqZj+fnU4cZGNbFpCpffiyhVsTig5TFCIs0iIJK+DYpBULn8rpQGO09tCWyof6o3nJCZ6A8exhAKzkahVjxZI3qiHYe3jwQXvq1VgScWUs1uPx1YXOxCPNaplgAGtsOjR9T1NtW3zIti065f6yYFrcCDRnDtJsSNc3BUZ+hMzrY="
    # GCLOUD_ACCOUNT
    - secure: "GurnDTea52C8+c3HLmd5zXMlZT0o/nfDOQi+51p9sl8xto7prk10tQfmFKQaygqKdyRIX3vtZxU9GVavP6LJB7YAe4AU7fiN6IM/zX1YR+11PvZeOW8F6dIMIcwBiaEziF2I6Tu9b81oDGmdNNxKWBMHHdcBFIfmDYof7NCI1eagPIJYpT9rSq3KSK7TtMhk0XaC6k7KeoF6sNLBAgIqfYlN6uV0iyYJNY40O3AXAs9kvIJ30XSqVctuZLAJ3nOUV0xWtm/JYCExPoYOgnJvkkddlMfe2qsyYQiTXHZ3SzOADSWqgnXRCWEnF4P/fXaXF13RAcsIwNUZyd8HaPq3xt2zOUDGRaxlypYBseDZHCfSrAcO76w6Hi8VYNmIa6ms0+0nUBU3R+ul6atEHzJ6YUda9WvUAUND0mblBFJ8jZ4Re0H9ZKEfJtnq7Gddyu+vO3vllsBki9u6BYh9UeCerRVC37g+PDnmZFB7erxwOA1x7Od7ku1c7YyrRRCorSzBwqWEoudysZ48Q+hlfUnB9wzmkUPXsXT+jGC1dSBP07jHfTlg6aC2kOGxcFkLnAAEBcCKGeLr7kLBL8DTmMCMKRiIIYDUFRNF5BhvNJNqROjIpICDD5NKHcJbNSyj62LrNxORiSSxamKlbfdGCymEtRK0xR0ypPQYJqLkErp/BDU="
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - tools

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".+"

before_install:
  - openssl aes-256-cbc -K $encrypted_b23950c7c963_key -iv $encrypted_b23950c7c963_iv -in ncryptf-travisci-2d6108f9a4f5.json.enc -out $HOME/ncryptf-travisci-2d6108f9a4f5.json -d
  - echo yes | sdkmanager tools "platform-tools" "build-tools;$ANDROID_BUILD_TOOLS"

install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud components update
  - gcloud version
  - gcloud config set project $GCLOUD_PROJECT
  - gcloud auth activate-service-account $GCLOUD_ACCOUNT --key-file $HOME/ncryptf-travisci-2d6108f9a4f5.json
  - rm $HOME/ncryptf-travisci-2d6108f9a4f5.json

script:
  - "./gradlew clean build --stacktrace --no-daemon"
  - "./gradlew :app:assembleDebug --no-daemon"
  - "./gradlew :app:assembleDebugAndroidTest --no-daemon"
  - gcloud firebase test android run --type instrumentation --test ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --os-version-ids 19,21,24,26,28 --device-ids NexusLowRes,Nexus5 --app ./app/dummy.apk --no-record-video --no-performance-metrics --timeout 10m