sudo: required
language: android

env:
  matrix:
    - ANDROID_API=19 ANDROID_BUILD_TOOLS=19.1.0
    - ANDROID_API=24 ANDROID_BUILD_TOOLS=24.0.2
    - ANDROID_API=28 ANDROID_BUILD_TOOLS=28.0.3
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - tools # This isn't redundant

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - '.+'

before_install:
  - echo yes | sdkmanager tools "platform-tools" "build-tools;$ANDROID_BUILD_TOOLS"

script: 
  - "./gradlew clean build --stacktrace"
  - "./gradlew :app:assembleDebug"
  - "./gradlew :app:assembleDebugAndroidTest"