sudo: required
language: android

env:
  matrix:
    - ANDROID_API=28 ANDROID_BUILD_TOOLS=28.0.3

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - tools # This isn't redundant

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - '.+'

before_install:
  - echo yes | sdkmanager tools "platform-tools" "build-tools;$ANDROID_BUILD_TOOLS"

script: 
  - "./gradlew clean build --stacktrace"
  - "./gradlew :app:assembleDebug"
  - "./gradlew :app:assembleDebugAndroidTest"
#  - gcloud firebase test android run \
#      --type instrumentation \
#      --test ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
#      --os-version-ids 19,20,21,22,23,24,25,26,27,28 \
#      --device-ids NexusLowRes,Nexus5 \
#      --app ./app/dummy.apk \
#      --no-record-video \
#      --no-performance-metrics